// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Flags potentially suspicious behavior based on head movements and contextual cues.
 *
 * - flagSuspiciousBehavior - A function that flags potentially suspicious behavior.
 * - FlagSuspiciousBehaviorInput - The input type for the flagSuspiciousBehavior function.
 * - FlagSuspiciousBehaviorOutput - The return type for the flagSuspiciousBehavior function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const FlagSuspiciousBehaviorInputSchema = z.object({
  videoDataUri: z
    .string()
    .describe(
      "A video feed of the candidate, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
  headMovementDescription: z.string().describe('The description of the candidate head movement.'),
  contextualCues: z.string().describe('Any additional contextual cues or observations.'),
});
export type FlagSuspiciousBehaviorInput = z.infer<typeof FlagSuspiciousBehaviorInputSchema>;

const FlagSuspiciousBehaviorOutputSchema = z.object({
  isSuspicious: z.boolean().describe('Whether or not the behavior is suspicious.'),
  reason: z.string().describe('The reasoning behind the suspicious flag.'),
});
export type FlagSuspiciousBehaviorOutput = z.infer<typeof FlagSuspiciousBehaviorOutputSchema>;

export async function flagSuspiciousBehavior(input: FlagSuspiciousBehaviorInput): Promise<FlagSuspiciousBehaviorOutput> {
  return flagSuspiciousBehaviorFlow(input);
}

const prompt = ai.definePrompt({
  name: 'flagSuspiciousBehaviorPrompt',
  input: {schema: FlagSuspiciousBehaviorInputSchema},
  output: {schema: FlagSuspiciousBehaviorOutputSchema},
  prompt: `You are an AI proctor tasked with identifying potentially suspicious behavior during an exam.

  You will analyze the candidate's head movements, contextual cues, and video feed to determine if cheating is likely.
  If head movements are jerky or suspicious, and the contextual cues suggest cheating set isSuspicious field to true, and explain why.

  Head Movement Description: {{{headMovementDescription}}}
  Contextual Cues: {{{contextualCues}}}
  Video Feed: {{media url=videoDataUri}}
  `,
});

const flagSuspiciousBehaviorFlow = ai.defineFlow(
  {
    name: 'flagSuspiciousBehaviorFlow',
    inputSchema: FlagSuspiciousBehaviorInputSchema,
    outputSchema: FlagSuspiciousBehaviorOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
