// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Flags potentially suspicious behavior based on head movements and contextual cues.
 *
 * - flagSuspiciousBehavior - A function that flags potentially suspicious behavior.
 * - FlagSuspiciousBehaviorInput - The input type for the flagSuspiciousBehavior function.
 * - FlagSuspiciousBehaviorOutput - The return type for the flagSuspiciousBehavior function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const FlagSuspiciousBehaviorInputSchema = z.object({
  videoDataUri: z
    .string()
    .describe(
      "A video feed of the candidate, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
  headMovementDescription: z.string().describe('The description of the candidate head movement.'),
  contextualCues: z.string().describe('Any additional contextual cues or observations.'),
});
export type FlagSuspiciousBehaviorInput = z.infer<typeof FlagSuspiciousBehaviorInputSchema>;

const FlagSuspiciousBehaviorOutputSchema = z.object({
  isSuspicious: z.boolean().describe('Whether or not the behavior is suspicious.'),
  reason: z.string().describe('The reasoning behind the suspicious flag.'),
});
export type FlagSuspiciousBehaviorOutput = z.infer<typeof FlagSuspiciousBehaviorOutputSchema>;

export async function flagSuspiciousBehavior(input: FlagSuspiciousBehaviorInput): Promise<FlagSuspiciousBehaviorOutput> {
  return flagSuspiciousBehaviorFlow(input);
}

const prompt = ai.definePrompt({
  name: 'flagSuspiciousBehaviorPrompt',
  input: {schema: FlagSuspiciousBehaviorInputSchema},
  output: {schema: FlagSuspiciousBehaviorOutputSchema},
  prompt: `You are an expert AI proctor with a high degree of accuracy, tasked with identifying potentially suspicious behavior during an online exam. Your primary goal is to avoid false positives. Only flag behavior when there is strong evidence of cheating.

Analyze the provided information: the candidate's head movements, contextual cues, and a single frame from their video feed.

**Analysis Criteria:**
- **Normal Behavior (NOT suspicious):**
    - Briefly looking away from the screen.
    - Mumbling or reading the question aloud.
    - Thinking, pausing, or looking up thoughtfully.
    - Fidgeting or adjusting position.
- **Suspicious Behavior (Potentially Cheating):**
    - Repeatedly looking down at a lap or desk, off-screen, for extended periods.
    - Clearly interacting with another person or using an unauthorized device (like a phone).
    - Leaving the view of the camera for an extended period.
    - Consistent eye movement towards a single off-screen location.

**Your Task:**
Based on the following data, determine if the behavior is suspicious. Set 'isSuspicious' to true ONLY if you are confident that cheating is occurring. Otherwise, set it to false. Provide a brief, clear reason for your decision.

**Candidate Data:**
- **Head Movement Description:** {{{headMovementDescription}}}
- **Contextual Cues:** {{{contextualCues}}}
- **Video Frame:** {{media url=videoDataUri}}
  `,
});

const flagSuspiciousBehaviorFlow = ai.defineFlow(
  {
    name: 'flagSuspiciousBehaviorFlow',
    inputSchema: FlagSuspiciousBehaviorInputSchema,
    outputSchema: FlagSuspiciousBehaviorOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
